// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjsYPzrKzzBfBJ-y1_cISICen-PGqPXQ',
    appId: '1:281266936229:web:8d391af40735e2bb70f04c',
    messagingSenderId: '281266936229',
    projectId: 'clonewhatsapp-ac4de',
    authDomain: 'clonewhatsapp-ac4de.firebaseapp.com',
    storageBucket: 'clonewhatsapp-ac4de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDAVHufvSntZATBekzBd9i7tkj3IRVtYI',
    appId: '1:281266936229:android:67fd8b1e721171f670f04c',
    messagingSenderId: '281266936229',
    projectId: 'clonewhatsapp-ac4de',
    storageBucket: 'clonewhatsapp-ac4de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi4fmmTbBZjnMOPFaikIOKb7zvz3AdhsQ',
    appId: '1:281266936229:ios:1c997d42c7197f4e70f04c',
    messagingSenderId: '281266936229',
    projectId: 'clonewhatsapp-ac4de',
    storageBucket: 'clonewhatsapp-ac4de.appspot.com',
    iosBundleId: 'com.example.flutterApplicationWa',
  );
}
